name: Node.js Build and Deploy

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  prebuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  deploy:
    needs: prebuild
    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
          context: .
          file: ./Dockerfile  # Path to your Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ecomart:latest  # Replace with your Docker Hub username and image name